version: "3.4"

services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=poster
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=posts
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main

volumes:
  postgres-data:

networks:
  main:
