name = "ricardobusquet"
type = "javascript"

zone_id = ""
account_id = ""
route = "*.ricardobusquet.com/*"
workers_dev = false

compatibility_date = "2021-11-24"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"
